name: Decision Tree
classifier:
  estimator:
    _target_: sklearn.tree.DecisionTreeClassifier
  multioutput: true
regressor:
  estimator:
    _target_: sklearn.tree.DecisionTreeRegressor
  multioutput: true
