name: Decision Tree
classifier:
  estimator:
    _target_: sklearn.tree.DecisionTreeClassifier
  multivariate: true
regressor:
  estimator:
    _target_: sklearn.tree.DecisionTreeRegressor
  multivariate: true
