name: TabNet
regressor:
  estimator:
    _target_: fseval.estimators.TabNetRegressor
  multioutput: true
classifier:
  estimator:
    _target_: pytorch_tabnet.tab_model.TabNetClassifier
  multioutput: true
