name: Synthetic classification dataset - easy
task: classification
adapter:
  _target_: sklearn.datasets.make_classification
  n_samples: 5000
  n_features: 4
  n_informative: 2
  n_redundant: 0
  n_repeated: 0
  n_classes: 2
  n_clusters_per_class: 2
  class_sep: 1.25
  random_state: 0
feature_importances:
  X[:, 0:1]: 1.0