name: Synthetic make_classification dataset (hard)
task: classification
adapter:
  _target_: sklearn.datasets.make_classification
  n_samples: 10000
  n_features: 20
  n_informative: 4
  n_redundant: 0
  n_repeated: 0
  n_classes: 2
  n_clusters_per_class: 2
  class_sep: 0.75
  random_state: 0
feature_importances:
  X[:, 0:3]: 1.0