defaults:
  - _self_
  - base_pipeline_config
  - override dataset: synthetic
  - override validator: knn
  - override /callbacks:
      - to_csv

n_bootstraps: 1

callbacks:
  to_csv:
    dir: /Users/dunnkers/Downloads/results_dir
