project: toy-wandb-fs
dataset:
  _target_: fseval.datasets.Dataset
  task: classification
cv:
  _target_: fseval.cv.CrossValidator
resample:
  _target_: fseval.resampling.Resample
ranker:
  _target_: fseval.rankers.Ranker
  task: ${dataset.task}
defaults:
  - dataset: iris
  - cv: train_test_split
  - resample: bootstrap
  - ranker: chi2
  - validator: dt