project: toy-wandb-fs
cv_fold: 0
bootstrap:
  random_state: 0
defaults:
  - dataset: iris
  - cv: train_test_split
  - ranker: chi2
  - validator: dt
# task:
#   fold: 0
# cv:
#   random_state: 0
#   test_size: 0.25
# bootstrap:
#   random_state: 0
#   replace: true
# defaults:
#   - task: rank
#   - ranker: tabnet_regressor
#   - validator: dt
#   - datasrc: xor
#   - cv: train_test_split