project: toy-wandb-fs
hydra:
  help:
    app_name: fseval
    header: |
      fseval benchmarking library.

defaults:
  - base_config
  - dataset: xor
  - cv: train_test_split
  - resample: bootstrap
  - ranker: tabnet
  - validator: dt
ranker:
  task: ${dataset.task}
validator:
  task: ${dataset.task}