project: toy-wandb-fs
defaults:
  - base_config
  - dataset: iris
  - cv: train_test_split
  - resample: bootstrap
  - ranker: chi2
  - validator: dt
ranker:
  task: ${dataset.task}
validator:
  task: ${dataset.task}