hydra:
  help:
    app_name: fseval
    header: |
      fseval benchmarking library.

defaults:
  - base_config
  - dataset: iris
  - cv: train_test_split
  - resample: bootstrap
  - pipeline: rank_and_validate
  - callbacks:
    - stdout
    - wandb
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog