hydra:
  help:
    app_name: fseval
    header: |
      fseval benchmarking library.

defaults:
  - base_config
  - dataset: iris
  - cv: train_test_split
  - resample: bootstrap
  - pipeline: run_estimator
  - callbacks:
    - stdout
    - wandb
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
callbacks:
  wandb:
    job_type: ${pipeline.name}
    project: toy-wandb-fs
    config:
      dataset:
        something: 5